# Serving HTML through API Gateway for AWS Lambda
service: pelias-stitch
provider:
  name: aws
  runtime: nodejs16.x
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.LAMBDA_EXEC_SG}
    subnetIds:
      - ${self:custom.secrets.LAMBDA_EXEC_SUBNET}
  environment:
    GEOCODER: ${self:custom.secrets.GEOCODER}
    TRANSIT_GEOCODER: ${self:custom.secrets.TRANSIT_GEOCODER}
    TRANSIT_BASE_URL: ${self:custom.secrets.TRANSIT_BASE_URL}
    # Pelias instance of Geocode.Earth, with street and landmarks
    GEOCODE_EARTH_URL: ${self:custom.secrets.GEOCODE_EARTH_URL, null}
    GEOCODER_API_KEY: ${self:custom.secrets.GEOCODER_API_KEY, null}
    # Pelias instance that is self-hosted, with GTFS stops and CSV POIs
    CUSTOM_PELIAS_URL: ${self:custom.secrets.CUSTOM_PELIAS_URL, null}
    # Used to logging to Bugsnag
    BUGSNAG_NOTIFIER_KEY: ${self:custom.secrets.BUGSNAG_NOTIFIER_KEY}
    REDIS_HOST: ${self:custom.secrets.REDIS_HOST, null}
    REDIS_KEY: ${self:custom.secrets.REDIS_KEY, null}
    # Secondary Geocoder config
    SECONDARY_GEOCODER: ${self:custom.secrets.SECONDARY_GEOCODER, null}
    SECONDARY_GEOCODER_API_KEY: ${self:custom.secrets.SECONDARY_GEOCODER_API_KEY, null}
    SECONDARY_GEOCODE_EARTH_URL: ${self:custom.secrets.SECONDARY_GEOCODE_EARTH_URL, null}
custom:
  secrets: ${file(env.yml)}
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 3600 # defaults to the maximum allowed: 3600
functions:
  autocomplete:
    handler: handler.autocomplete
    events:
      - http:
          method: get
          cors: true
          path: autocomplete
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.querystring.text
  search:
    handler: handler.search
    events:
      - http:
          method: get
          cors: true
          path: search
  reverse:
    handler: handler.reverse
    events:
      - http:
          method: get
          cors: true
          path: reverse
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-api-gateway-caching
